/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package execicio;

import javax.swing.JOptionPane;

/**
 *
 * @author tiago
 */
public class CaixaOpcao extends javax.swing.JPanel {

    /**
     * Creates new form CaixaOpcao
     */
    public CaixaOpcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ckIngles = new javax.swing.JCheckBox();
        ckInformatica = new javax.swing.JCheckBox();
        btVerificar = new javax.swing.JButton();
        btMarcar = new javax.swing.JButton();
        btDesmarcar = new javax.swing.JButton();

        ckIngles.setText("Inglês");

        ckInformatica.setText("Informática");

        btVerificar.setText("Verificar");
        btVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarActionPerformed(evt);
            }
        });

        btMarcar.setText("Marcar");
        btMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMarcarActionPerformed(evt);
            }
        });

        btDesmarcar.setText("Desmarcar");
        btDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesmarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckIngles)
                    .addComponent(ckInformatica)
                    .addComponent(btVerificar)
                    .addComponent(btMarcar)
                    .addComponent(btDesmarcar))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btDesmarcar, btMarcar, btVerificar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckIngles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckInformatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMarcar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDesmarcar)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarActionPerformed
        
        String selecionados = "Selecionados: ";
        
        if (ckIngles.isSelected()) {
            
            selecionados += "\nInglês";
            
        }
        
        if (ckInformatica.isSelected()) {
            
            selecionados += "\nInformática";
            
        }
        
        JOptionPane.showMessageDialog(null, selecionados);
        
    }//GEN-LAST:event_btVerificarActionPerformed

    private void btMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarcarActionPerformed
        
        ckIngles.setSelected(true);
        ckInformatica.setSelected(true);
        
    }//GEN-LAST:event_btMarcarActionPerformed

    private void btDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesmarcarActionPerformed
        
        ckIngles.setSelected(false);
        ckInformatica.setSelected(false);
        
    }//GEN-LAST:event_btDesmarcarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDesmarcar;
    private javax.swing.JButton btMarcar;
    private javax.swing.JButton btVerificar;
    private javax.swing.JCheckBox ckInformatica;
    private javax.swing.JCheckBox ckIngles;
    // End of variables declaration//GEN-END:variables
}
