/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package execicio;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Login
 */
public class MenuPrincipal extends javax.swing.JFrame {
  
           
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        mnExemplos = new javax.swing.JMenu();
        miBotao = new javax.swing.JMenuItem();
        miCaixaOpcao = new javax.swing.JMenuItem();
        miRadio = new javax.swing.JMenuItem();
        miLabels = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        contentPane.setLayout(new java.awt.CardLayout());

        mnArquivo.setMnemonic('A');
        mnArquivo.setText("Arquivo");

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miSair);

        jMenuBar1.add(mnArquivo);

        mnExemplos.setMnemonic('E');
        mnExemplos.setText("Exemplos");

        miBotao.setText("Botao");
        miBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBotaoActionPerformed(evt);
            }
        });
        mnExemplos.add(miBotao);

        miCaixaOpcao.setText("Caixa de Opção");
        miCaixaOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCaixaOpcaoActionPerformed(evt);
            }
        });
        mnExemplos.add(miCaixaOpcao);

        miRadio.setText("Botao de Radio");
        miRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRadioActionPerformed(evt);
            }
        });
        mnExemplos.add(miRadio);

        miLabels.setText("Labels");
        miLabels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLabelsActionPerformed(evt);
            }
        });
        mnExemplos.add(miLabels);

        jMenuBar1.add(mnExemplos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBotaoActionPerformed
        Botao botao = new Botao();
        contentPane.removeAll();
        contentPane.add(botao);
        contentPane.validate();
    }//GEN-LAST:event_miBotaoActionPerformed

    private void miCaixaOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCaixaOpcaoActionPerformed
        
        CaixaOpcao caixaOpcao = new CaixaOpcao();
        contentPane.removeAll();
        contentPane.add(caixaOpcao);
        contentPane.validate();
        
    }//GEN-LAST:event_miCaixaOpcaoActionPerformed

    private void miRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRadioActionPerformed
        
        Radio radio = new Radio();
        contentPane.removeAll();
        contentPane.add(radio);
        contentPane.validate();
        
    }//GEN-LAST:event_miRadioActionPerformed

    private void miLabelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLabelsActionPerformed
        
        Lables lables = new Lables();
        contentPane.removeAll();
        contentPane.add(lables);
        contentPane.validate();
        
    }//GEN-LAST:event_miLabelsActionPerformed

    
    public static void abrir() {
        
        MenuPrincipal frame = new MenuPrincipal();  
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2, 
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miBotao;
    private javax.swing.JMenuItem miCaixaOpcao;
    private javax.swing.JMenuItem miLabels;
    private javax.swing.JMenuItem miRadio;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnExemplos;
    // End of variables declaration//GEN-END:variables
}
